#!/bin/bash
#
# Bash command exection library with error logging
#
# Dependency: bash-lib-logging
#

source lib/bash-lib-logging

__initExeCmdLibrary()
{
	(( ${__EXECMD_LIB_INITIALIZED__} )) && return
	readonly __EXECMD_LIB_INITIALIZED__=1
}

exeCmd()
{

        local cmd=$1
        local errorMsg=$2
        local successMsg=$3 
        set -e
        set -o pipefail 
        if [ -z "${cmd}" ]; then
                abort "(exeCmd): command not provided"
        else
                if [ -z "${errorMsg}" ]; then
                        errorMsg="Error: Command execution failed. Command: [${cmd//\"/\\\"}]"
                else
                        errorMsg="${errorMsg//\"/\\\"}"
                fi
                if [ -z "${successMsg}" ]; then
                        successMsg=""
                else
                        successMsg="${successMsg//\"/\\\"}"
                fi
                local _CMD="${cmd}; 
                                if (( \$? )); then 
                                        echo \"${errorMsg}\";
                                        echo 'Aborting...';
                                        exit 1;
                                else
                                        if [ ! -z \"${successMsg}\" ]; then
                                                echo \"${successMsg}\";
                                        fi;
                                fi"
                bash -c "${_CMD}" 2>&1 | logPipe
        fi
        set +o pipefail 
        set +e
}

exeCmd_asUser()
{
        local user=${1}
        local cmd=${2}
        local errorMsg=${3}
        local successMsg=${4}
        if [ -z "${user}" ]; then
                abort "(exeCmd_asUser): user name not provided"
        fi
        if [ -z "${cmd}" ]; then
                abort "(exeCmd_asUser): command not provided"
        else
                local _CMD="runuser -l ${user} -c '${cmd}'"
                exeCmd "${_CMD}" "${errorMsg}" "${successMsg}"
        fi
}

#
# NOTE: Called function must return
#       >= 1 to indicate success or 
#          0 to indicate failure
#       Otherwise this function will fail
#
exeFunc()
{
        local func=$1
        local errorMsg=$2
        local successMsg=$3
        if [ -z "${func}" ]; then
                abort "(exeFunc): Function name not provided"
        fi
        if (( $(${func}) )); then
                if [ ! -z "${successMsg}" ]; then
                        log "${successMsg}"
                fi
        else
                if [ -z "${errorMsg}" ]; then
			log "ERROR: Failed to execute function: ${func}"
		else
                        abort "${errorMsg}"
                fi
        fi
} 

__initExeCmdLibrary

#::END::
